# Generated by Django 4.2.7 on 2024-02-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StudentMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.CharField(max_length=50)),
                ('m1_q1_marks', models.FloatField(default=None, null=True)),
                ('m1_q2_marks', models.FloatField(default=None, null=True)),
                ('m1_q3_marks', models.FloatField(default=None, null=True)),
                ('m1_q4_marks', models.FloatField(default=None, null=True)),
                ('m1_objective_marks', models.FloatField(default=None, null=True)),
                ('m1_assignment_marks', models.FloatField(default=None, null=True)),
                ('m2_q1_marks', models.FloatField(default=None, null=True)),
                ('m2_q2_marks', models.FloatField(default=None, null=True)),
                ('m2_q3_marks', models.FloatField(default=None, null=True)),
                ('m2_q4_marks', models.FloatField(default=None, null=True)),
                ('m2_objective_marks', models.FloatField(default=None, null=True)),
                ('m2_assignment_marks', models.FloatField(default=None, null=True)),
                ('ext_marks', models.FloatField(default=None, null=True)),
            ],
        ),
    ]
