# Generated by Django 4.2.7 on 2024-02-28 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attainment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentsmarks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.studentmark')),
            ],
        ),
    ]
