# Generated by Django 4.2.7 on 2024-02-29 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0006_remove_co_po_mapping_po_mapped_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CO_PO_Matrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po1', models.CharField(choices=[('-', '-'), (1, 1), (2, 2), (3, 3)], default='-', max_length=10)),
                ('co', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.co')),
            ],
        ),
    ]
