# Generated by Django 4.2.7 on 2024-02-29 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0007_co_po_matrix'),
    ]

    operations = [
        migrations.AddField(
            model_name='co_po_matrix',
            name='po10',
            field=models.CharField(choices=[('-', '-'), (1, 1), (2, 2), (3, 3)], default='-', max_length=10),
        ),
        migrations.AddField(
            model_name='co_po_matrix',
            name='po11',
            field=models.CharField(choices=[('-', '-'), (1, 1), (2, 2), (3, 3)], default='-', max_length=10),
        ),
        migrations.AddField(
            model_name='co_po_matrix',
            name='po12',
            field=models.CharField(choices=[('-', '-'), (1, 1), (2, 2), (3, 3)], default='-', max_length=10),
        ),
        migrations.AddField(
            model_name='co_po_matrix',
            name='po2',
            field=models.CharField(choices=[('-', '-'), (1, 1), (2, 2), (3, 3)], default='-', max_length=10),
        ),
        migrations.AddField(
            model_name='co_po_matrix',
            name='po3',
            field=models.CharField(choices=[('-', '-'), (1, 1), (2, 2), (3, 3)], default='-', max_length=10),
        ),
        migrations.AddField(
            model_name='co_po_matrix',
            name='po4',
            field=models.CharField(choices=[('-', '-'), (1, 1), (2, 2), (3, 3)], default='-', max_length=10),
        ),
        migrations.AddField(
            model_name='co_po_matrix',
            name='po5',
            field=models.CharField(choices=[('-', '-'), (1, 1), (2, 2), (3, 3)], default='-', max_length=10),
        ),
        migrations.AddField(
            model_name='co_po_matrix',
            name='po6',
            field=models.CharField(choices=[('-', '-'), (1, 1), (2, 2), (3, 3)], default='-', max_length=10),
        ),
        migrations.AddField(
            model_name='co_po_matrix',
            name='po7',
            field=models.CharField(choices=[('-', '-'), (1, 1), (2, 2), (3, 3)], default='-', max_length=10),
        ),
        migrations.AddField(
            model_name='co_po_matrix',
            name='po8',
            field=models.CharField(choices=[('-', '-'), (1, 1), (2, 2), (3, 3)], default='-', max_length=10),
        ),
        migrations.AddField(
            model_name='co_po_matrix',
            name='po9',
            field=models.CharField(choices=[('-', '-'), (1, 1), (2, 2), (3, 3)], default='-', max_length=10),
        ),
    ]
