# Generated by Django 4.2.7 on 2024-02-29 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0008_co_po_matrix_po10_co_po_matrix_po11_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='co_po_matrix',
            name='po1',
            field=models.CharField(choices=[('-', '-'), ('1', 1), ('2', 2), ('3', 3)], default='-', max_length=10),
        ),
        migrations.AlterField(
            model_name='co_po_matrix',
            name='po10',
            field=models.CharField(choices=[('-', '-'), ('1', 1), ('2', 2), ('3', 3)], default='-', max_length=10),
        ),
        migrations.AlterField(
            model_name='co_po_matrix',
            name='po11',
            field=models.CharField(choices=[('-', '-'), ('1', 1), ('2', 2), ('3', 3)], default='-', max_length=10),
        ),
        migrations.AlterField(
            model_name='co_po_matrix',
            name='po12',
            field=models.CharField(choices=[('-', '-'), ('1', 1), ('2', 2), ('3', 3)], default='-', max_length=10),
        ),
        migrations.AlterField(
            model_name='co_po_matrix',
            name='po2',
            field=models.CharField(choices=[('-', '-'), ('1', 1), ('2', 2), ('3', 3)], default='-', max_length=10),
        ),
        migrations.AlterField(
            model_name='co_po_matrix',
            name='po3',
            field=models.CharField(choices=[('-', '-'), ('1', 1), ('2', 2), ('3', 3)], default='-', max_length=10),
        ),
        migrations.AlterField(
            model_name='co_po_matrix',
            name='po4',
            field=models.CharField(choices=[('-', '-'), ('1', 1), ('2', 2), ('3', 3)], default='-', max_length=10),
        ),
        migrations.AlterField(
            model_name='co_po_matrix',
            name='po5',
            field=models.CharField(choices=[('-', '-'), ('1', 1), ('2', 2), ('3', 3)], default='-', max_length=10),
        ),
        migrations.AlterField(
            model_name='co_po_matrix',
            name='po6',
            field=models.CharField(choices=[('-', '-'), ('1', 1), ('2', 2), ('3', 3)], default='-', max_length=10),
        ),
        migrations.AlterField(
            model_name='co_po_matrix',
            name='po7',
            field=models.CharField(choices=[('-', '-'), ('1', 1), ('2', 2), ('3', 3)], default='-', max_length=10),
        ),
        migrations.AlterField(
            model_name='co_po_matrix',
            name='po8',
            field=models.CharField(choices=[('-', '-'), ('1', 1), ('2', 2), ('3', 3)], default='-', max_length=10),
        ),
        migrations.AlterField(
            model_name='co_po_matrix',
            name='po9',
            field=models.CharField(choices=[('-', '-'), ('1', 1), ('2', 2), ('3', 3)], default='-', max_length=10),
        ),
    ]
