# Generated by Django 4.2.7 on 2024-02-29 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0011_alter_co_po_matrix_po1_alter_co_po_matrix_po10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='co_pso_matrix',
            name='pso1',
            field=models.CharField(choices=[('-', None), ('1', 1), ('2', 2), ('3', 3)], default='-', max_length=10),
        ),
        migrations.AlterField(
            model_name='co_pso_matrix',
            name='pso2',
            field=models.CharField(choices=[('-', None), ('1', 1), ('2', 2), ('3', 3)], default='-', max_length=10),
        ),
        migrations.AlterField(
            model_name='co_pso_matrix',
            name='pso3',
            field=models.CharField(choices=[('-', None), ('1', 1), ('2', 2), ('3', 3)], default='-', max_length=10),
        ),
        migrations.CreateModel(
            name='Indirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high', models.IntegerField(null=True)),
                ('medium', models.IntegerField(null=True)),
                ('low', models.IntegerField(null=True)),
                ('attainment', models.FloatField(null=True)),
                ('co', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.co')),
            ],
        ),
    ]
