# Generated by Django 4.2.7 on 2024-02-29 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0012_alter_co_pso_matrix_pso1_alter_co_pso_matrix_pso2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indirect',
            name='attainment',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='indirect',
            name='high',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='indirect',
            name='low',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='indirect',
            name='medium',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.CreateModel(
            name='CO_Attainment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal', models.FloatField(default=0, null=True)),
                ('external', models.FloatField(default=0, null=True)),
                ('direct', models.FloatField(default=0, null=True)),
                ('indirect', models.FloatField(default=0, null=True)),
                ('final', models.FloatField(default=0, null=True)),
                ('co', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.co')),
            ],
        ),
    ]
