# Generated by Django 4.2.7 on 2024-02-29 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0013_alter_indirect_attainment_alter_indirect_high_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='co',
            name='co',
            field=models.CharField(choices=[('-', '-'), ('CO1', 'CO1'), ('CO2', 'CO2'), ('CO3', 'CO3'), ('CO4', 'CO4'), ('CO5', 'CO5'), ('CO6', 'CO6')], default='-', max_length=500),
        ),
        migrations.AlterField(
            model_name='po',
            name='po',
            field=models.CharField(choices=[('-', '-'), ('PO1', 'PO1'), ('PO2', 'PO2'), ('PO3', 'PO3'), ('PO4', 'PO4'), ('PO5', 'PO5'), ('PO6', 'PO6'), ('PO7', 'PO7'), ('PO8', 'PO8'), ('PO9', 'PO9'), ('PO10', 'PO10'), ('PO11', 'PO11'), ('PO12', 'PO12')], default='-', max_length=500),
        ),
        migrations.CreateModel(
            name='Mid1_QP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('co_mapped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.co')),
            ],
        ),
    ]
