# Generated by Django 4.2.7 on 2024-03-02 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0015_mid2_qp'),
    ]

    operations = [
        migrations.AddField(
            model_name='co_po_matrix',
            name='pso1',
            field=models.CharField(choices=[('-', None), ('1', 1), ('2', 2), ('3', 3)], default='-', max_length=10),
        ),
        migrations.AddField(
            model_name='co_po_matrix',
            name='pso2',
            field=models.CharField(choices=[('-', None), ('1', 1), ('2', 2), ('3', 3)], default='-', max_length=10),
        ),
        migrations.AddField(
            model_name='co_po_matrix',
            name='pso3',
            field=models.CharField(choices=[('-', None), ('1', 1), ('2', 2), ('3', 3)], default='-', max_length=10),
        ),
    ]
