# Generated by Django 4.2.7 on 2024-03-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0016_co_po_matrix_pso1_co_po_matrix_pso2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mid1_qp',
            name='attainment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mid2_qp',
            name='attainment',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='CO_PSO_Matrix',
        ),
    ]
