# Generated by Django 4.2.7 on 2024-03-02 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0017_mid1_qp_attainment_mid2_qp_attainment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mid1_qp',
            old_name='attainment',
            new_name='attainment_level',
        ),
        migrations.RenameField(
            model_name='mid2_qp',
            old_name='attainment',
            new_name='attainment_level',
        ),
    ]
