# Generated by Django 4.2.7 on 2024-03-02 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0019_course_attainment_delete_co_attainment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.CharField(max_length=50)),
                ('ext', models.FloatField(default=None, null=True)),
                ('mid1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.mid1_qp')),
                ('mid2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.mid2_qp')),
            ],
        ),
    ]
