# Generated by Django 4.2.7 on 2024-03-02 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0020_student_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rollno', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SEE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.FloatField(default=None, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.student')),
            ],
        ),
        migrations.CreateModel(
            name='QP_mid2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('co_mapped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.co')),
            ],
        ),
        migrations.CreateModel(
            name='QP_mid1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('co_mapped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.co')),
            ],
        ),
        migrations.CreateModel(
            name='Mid2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.FloatField(default=None, null=True)),
                ('mid2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.qp_mid2')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Mid1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.FloatField(default=None, null=True)),
                ('mid1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.qp_mid1')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.student')),
            ],
        ),
    ]
