# Generated by Django 4.2.7 on 2024-03-02 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0021_student_see_qp_mid2_qp_mid1_mid2_mid1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mid1',
            old_name='mid1',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='mid2',
            old_name='mid2',
            new_name='question',
        ),
    ]
