# Generated by Django 4.2.7 on 2024-03-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0023_alter_student_name_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='co_mapped',
        ),
        migrations.AddField(
            model_name='question',
            name='co_mapped',
            field=models.ManyToManyField(to='testApp.co'),
        ),
    ]
