# Generated by Django 4.2.7 on 2024-03-02 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0024_remove_question_co_mapped_question_co_mapped'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='External_Question',
        ),
        migrations.CreateModel(
            name='Intenal_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('attainment_level', models.IntegerField(default=0)),
                ('co_mapped', models.ManyToManyField(to='testApp.co')),
            ],
        ),
    ]
