# Generated by Django 4.2.7 on 2024-03-03 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0026_course_attainment_direct_course_attainment_external_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PO_Attainment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attainment', models.FloatField(default=0, null=True)),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.po')),
            ],
        ),
    ]
