# Generated by Django 4.2.7 on 2024-03-03 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0027_po_attainment'),
    ]

    operations = [
        migrations.CreateModel(
            name='COt_POrPSO_Matrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('-', None), ('1', 1), ('2', 2), ('3', 3)], default='-', max_length=10)),
                ('co', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.co')),
            ],
        ),
    ]
