# Generated by Django 4.2.7 on 2024-03-03 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0028_cot_porpso_matrix'),
    ]

    operations = [
        migrations.AddField(
            model_name='cot_porpso_matrix',
            name='po',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testApp.po'),
            preserve_default=False,
        ),
    ]
