# Generated by Django 4.2.7 on 2024-03-03 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0029_cot_porpso_matrix_po'),
    ]

    operations = [
        migrations.DeleteModel(
            name='COt_POrPSO_Matrix',
        ),
    ]
